export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FULFILLED = 'FETCH_PRODUCTS_FULFILLED';
export const FETCH_PRODUCTS_REJECTED = 'FETCH_PRODUCTS_REJECTED';

export const FETCH_RANKINGS = 'FETCH_RANKINGS';
export const FETCH_RANKINGS_FULFILLED = 'FETCH_RANKINGS_FULFILLED';
export const FETCH_RANKINGS_REJECTED = 'FETCH_RANKINGS_REJECTED';
